# Generated by Django 4.2.4 on 2023-12-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_device_reading'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='description',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
