# Generated by Django 4.2.4 on 2023-10-02 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=128)),
                ('pw', models.CharField(max_length=128)),
                ('login_trials', models.IntegerField(default=0)),
                ('products', models.ManyToManyField(to='products.product')),
            ],
        ),
    ]
